### PR TITLE
Fixing share icon

### PR DESCRIPTION
**Pull request by carlosgonz0**

### CODE REVIEW

**Comment by elros34** [comment]
So you insist to use lower resolution than previously .. that is ok for my low resolution display. Have you checked that icon changed because according to my test change has no effect?

**Comment by elros34** [comment]
Looks like this icon is used for share plugin https://github.com/elros34/depecher/blob/next/icons/svgs/icon-m-depecher.svg, not sure what else could use it.

**Comment by carlosgonz0** [comment]
Sorry it my mistake. I will fix it.

**Comment by elros34** [comment]
I suggested that depeche.png but I didn't check it because such a change is not very relevant for me. Frankly I do not even get why share plugin use square icons.

Anyway you do not need to close PR and open another. You can always make correct changes and then git push --force.

**Pull request closed without merging**
